### ISSUE TITLE
Error when I try to update the plugin

### ISSUE THREAD

**Issue by RumbosN** [CrossGeeks/GeofencePlugin#25]
When I try to update Plugin.Geofence 1.0.1 to 1.5.4 or 1.4.0 nuget throw:
```
Failed to add reference. The package 'Plugin.Geofence' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.
```

Xamarin.Forms version 4.5.0.356

**Comment by LeoArgy** [comment]
Same problem here. Are you building with VS2019?  I found this from @jamesmontemagno
(https://github.com/Baseflow/XamarinMediaManager/issues/558)

if building in 2019 add

<DisableExtraReferences>true</DisableExtraReferences>
This will fix the nuget

**Comment by LeoArgy** [comment]
Dangit. It interpreted the dang code. 
`<DisableExtraReferences>true</DisableExtraReferences>`

**Comment by jamesmontemagno** [comment]
Easiest way it to ensure you have updated to Package References and then you won't have an issue.

**Comment by RumbosN** [comment]
@jamesmontemagno I solve this with:
1. I changed in project.iOS/packages.config the GeofencePlugin version to 1.5.4
2. In project.iOS.csproj remove
`<Reference Include="Plugin.Geofence.Abstractions, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL"><HintPath>..\..\packages\Plugin.Geofence.1.0.1\lib\Xamarin.iOS10\Plugin.Geofence.Abstractions.dll</HintPath>
</Reference>`
and changed the Plugin.Geofence referece to 
`<Reference Include="Plugin.Geofence, Version=1.4.0.0, Culture=neutral, processorArchitecture=MSIL">
<HintPath>..\..\packages\Plugin.Geofence.1.5.4\lib\xamarinios10\Plugin.Geofence.dll</HintPath>
</Reference>`
