### ISSUE TITLE
Radius?

### ISSUE THREAD

**Issue by napoleonjones** [CrossGeeks/GeofencePlugin#3]
What is the unit of measure for the radius?

**Comment by smrkamran** [comment]
Dont know why im getting `System.InvalidCastException: Specified cast is not valid.`  when i run `StartMonitoring` method.
installed `.NETStandard 1.6.1` and `Xamarin.GooglePlayServices.Location 60.1142.1`
not using Shared Project not PCL

**Comment by napoleonjones** [comment]
Are you passing in the correct data types.  I'm not receiving that error?

**Comment by smrkamran** [comment]
`CrossGeofence.Current.StartMonitoring(new GeofenceCircularRegion("MyRegioan", 31.475085, 
            74.305833, 200.0)
            {
                NotifyOnStay = true,
                StayedInThresholdDuration = TimeSpan.FromMinutes(5)
            });`

**Comment by smrkamran** [comment]
can you give me the access to your repository?

**Comment by napoleonjones** [comment]
No, it's private.

You should also move this to a new issue as it's totally unrelated to my question.

**Comment by smrkamran** [comment]
ok

**Comment by smrkamran** [comment]
bro at which place you are calling `StartMonitoring`? 
p.s sorry for creating noise on your issue

**Comment by napoleonjones** [comment]
its meters
