### ISSUE TITLE
[Android] Application crashes when I build 

### ISSUE THREAD

**Issue by lupialex** [CrossGeeks/GeofencePlugin#33]
Hello,
I created a Xamarin forms project and use GeofencePlugin (version 1.5.7), but when I build the application it crashes and obtains the following error:
`<my-project-android-path>/obj/Release/android/src/crc64c554f6b6abc76285/GeofenceImplementation.java(8,8): Error JAVAC0000:  error: GeofenceImplementation is not abstract and does not override abstract method onConnectionSuspended(int) in ConnectionCallbacks
public class GeofenceImplementation
 (JAVAC0000) (MyProject.Android) javac`

For more info:

- Visual studio for mac v 8.8.2 (build 41);
- Xamarin.Forms v4.8.0.1687;
-Android build version (Android 10(Q)).

Thanks in advanced

**Comment by dfilho** [comment]
Hi, 
I'm having the same issue, please, someone could help us?

Thanks!

**Comment by dfilho** [comment]
The new release resolved my problem, thank you!!
